{% set name = "small-text" %}
{% set version = "2.0.0.dev3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/small_text-{{ version }}.tar.gz
  sha256: 089a8afcb3eed8f0f0b13e1a3d16c826002c649d8da9e1ea5bd3ade8dccda5d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python 3.10
    - setuptools
    - conda-forge-ci-setup 3.17.1
  run:
    - dill >=0.3.7
    - numpy >=1.21.0
    - python >={{ python_min }}
    - scikit-learn >=0.24.1
    - scipy
    - tqdm
    - packaging
    - tokenizers >=0.11.5
    - tomli

test:
  imports:
    - small_text
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/webis-de/small-text
  summary: Active Learning for Text Classification in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://small-text.readthedocs.io/en/latest/
  dev_url: https://github.com/webis-de/small-text

extra:
  recipe-maintainers:
    - chschroeder
