{% set name = "small-text" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/small-text-{{ version }}.tar.gz
  sha256: bc89fa36b37161dc3f70e58d8375ff5e10a39e2bd1c5e9a651d822172a20b6c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dill
    - numpy >=1.20.0
    - python >=3.7
    - scikit-learn >=0.24.1
    - scipy
    - tqdm
    - packaging

test:
  imports:
    - small_text
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/webis-de/small-text
  summary: Active Learning for Text Classifcation in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://small-text.readthedocs.io/en/latest/
  dev_url: https://github.com/webis-de/small-text

extra:
  recipe-maintainers:
    - chschroeder
